import type { NextPage } from "next";
import Head from "next/head";
import { useEffect } from "react";
import { contract, getBlockNumber } from "../utils/ethersSetup";

const Home: NextPage = () => {
  getBlockNumber().then(console.log);

  contract.name().then(console.log);
  // useEffect(() => {
  //   getBlockNumber().then(console.log);
  // }, []);

  return (
    <div>
      <Head>
        <title>Wbtc dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>Hello</div>
    </div>
  );
};

export default Home;
