import type { NextPage } from "next";
import dynamic from "next/dynamic";
import Head from "next/head";
import { Suspense } from "react";

const EventList = dynamic(() => import("../components/EventList"), {
  suspense: true,
  ssr: false,
});

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Wbtc dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="text-3xl">hey</div>

      <Suspense fallback={<div>Loading...</div>}>
        <EventList />
      </Suspense>
    </div>
  );
};

export default Home;
